{
 "title": "Tap-Protocol",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "deployment", "query": { "query": "label_values(deployment)" } }
  ]
 },
 "panels": [
  { "title": "Protocol Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Token-Auth Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tap_protocol_getauthlistlength", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DMT Elements",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tap_protocol_getdmtelementslistlength",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Events Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tap_protocol_getsentlistlength", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Token Deploys Length",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tap_protocol_getdeploymentslength",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mint List Length",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tap_protocol_getmintlistlength" }
   ]
  },
  {
   "title": "Token Holders ${deployment}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tap_protocol_holders_count{deployment=~\"${deployment}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}